{
  "hash": "2f58cedcfcae3fe4fb04576065ca206d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regresión lineal simple\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Introducción\n\nPara entender el modelo de regresión lineal simple, volvamos al ejemplo del peso en niñas menores de 6 meses de la [**unidad anterior**](../unidad_2/03_inferencia.qmd#ejemplo-práctico-en-r), donde habíamos trazado una recta que nos ilustraba la relación lineal del peso en función de la edad.\n\nSegún el modelo estadístico para la función lineal de $Y$ según $X$:\n\n$$\nY(X) =  \\beta_0 + \\beta_1 + X_1\n$$\n\nHemos ajustado un modelo cuyos parámetros son:\n\n$$\n\\hat{y} = b_0 + b_1X_1\n$$\n\ndonde $b_1$ nos está indicando cuánto se modifica $\\hat{y}$ por cada unidad de aumento de $X_1$.\n\n$$\n\\hat{y} = 2468,9 + 100,7 \\: edad \\: (en \\: semanas) \n$$\n\nSe interpreta que por cada semana este grupo de lactantes ha aumentado en promedio 100 gramos, o que cada 1 mes (4 semanas) aumentan una media de 400 gramos.\n\nPodemos observar que hay una relación lineal y que esta relación no es perfecta. Existe cierta dispersión entre los puntos sugiriendo que alguna variación en el peso no se asocia con un incremento de la edad (por ejemplo dos lactantes de 15 semanas. Tienen la misma edad y 1.600 grs de diferencia. Cabría preguntarse si esas niñas que se \"alejan\" tanto de la recta de regresión no tienen algún antecedente distinto del resto). Más adelante veremos cómo se interpretan esas diferentes distancias entre las observaciones y la recta de regresión.\n\nAhora vamos a concentrarnos en la relación entre la varianza de la muestra, a través del desvío estándar ($ds = \\sqrt{varianza}$) y la magnitud de la asociación. Se muestran cuatro ejemplos en los cuáles se fue aumentando progresivamente el desvío estándar de los datos. Observen cómo a medida que aumenta la variabilidad entre los individuos va disminuyendo el coeficiente de correlación y el coeficiente $b_1$ (pendiente de la recta)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/rls-1-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nPodemos observar que cuanto mayor es la varianza en una muestra:\n\n- Mayor es la variabilidad de $y$ en torno a la recta de regresión\n\n- Mayor es la imprecisión asociada a la estimativa de los parámetros de regresión\n\n## Presupuestos del modelo\n\nCuando planeamos realizar un análisis de regresión con un conjunto de datos es necesario saber que para que podamos plantearlo adecuadamente deben cumplirse ciertas condiciones, que llamaremos Presupuestos del modelo:\n\n1.  Independencia: los valores de $y$ deben ser independientes unos de otros\n2.  Linealidad: la relación entre $x$ e $y$ debe ser una función lineal\n3.  Homocedasticidad: la varianza de $y$ debe mantenerse constante para los distintos valores de $x$\n4.  Normalidad: $y$ debe tener una distribución normal\n\n**¿Cómo se obtiene la recta de regresión? ¿Cómo se calculan los coeficientes de la regresión?**\n\nEn el ejemplo del peso según edad en niñas menores de 6 meses, la idea es encontrar una función lineal (que gráficamente es una recta) que aplicada a los valores de $x$ nos permita aproximar los valores de $y$. La ecuación de la recta que describe la relación entre $x$ e $y$:\n\n$$\n\\hat{y} = b_0 + b_1x\n$$\n\nPor muy bueno que sea el modelo de regresión $y$ e $\\hat{y}$ rara vez coincidirán.\n\nEntonces podríamos pensar que la mejor recta que permita predecir (o aproximar) los valores de $y$ en función de $x$ es aquella que minimice estos errores residuales (que algunos serán en más y otros serán en menos).\n\nGráficamente:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/rls-2-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\ndonde:\n\n- $\\hat{y}$ es la ecuación de la \"mejor\" recta que puede trazarse entre estos puntos\n\n- $b_0$ es la ordenada al origen o constante, también llamada alfa. Es el punto donde la recta de regresión corta al eje de ordenadas.\n\n- $b_1$ es la pendiente de la recta (más adelante veremos cuál es la interpretación de estos coeficientes).\n\nConsideremos qué pasa en el caso de la niña 7. Veamos las distancias para este punto.\n\n- $y_7$ es el valor \"real\" del peso de la niña 7.\n\n- $\\hat{y}_7$ es el valor estimado de $y$ que obtendremos a través de la regresión.\n\n- $y – \\hat{y} = e$ (residuo o error residual) es el desvío de $y$ del valor ajustado $\\hat{y}$ en la ecuación de la regresión estimada.\n\nPara poder operar con el valor de estos errores (ya que algunos tendrán valor positivo y otros valor negativo) se los eleva al cuadrado. Esta técnica se denomina **\"método de los mínimos cuadrados\"** y consiste en adoptar como estimativas de los parámetros de la regresión (o sea los coeficientes $b_0$ y $b_1$ y por ende la recta de regresión) los valores que minimizan la suma de los cuadrados de los residuos o error (**SCE**) para todas las observaciones de $y$. Lo podemos expresar así:\n\n$$\nSCE = \\sum{\\hat{e}^2} = \\sum{(y-\\hat{y})^2}\n$$\n\nSabíamos que:\n\n$$\n\\hat{y} = b_0 + b_1x\n$$\n\nEntonces si reemplazamos:\n\n$$\nSCE = \\sum_{i=1}^{i=n} (y_i-\\hat{y}_i)^2 =  \\sum_{i=1}^{i=n}(y_i-(\\hat{\\beta}_0 + \\hat{\\beta}_1x_1))^2\n$$\n\nEs posible obtener los estimadores $\\beta_1$ y $\\beta_0$.\n\n$$\n\\hat{\\beta}_1 = \\frac{\\sum_{i=1}^{n}(x_i - \\bar{x})(y_i - \\bar{y})}{\\sum_{i=1}^{n}(x_i-\\bar{x})^2} = \\frac{S_{xy}}{S_{xx}}\n$$\n\nOtra fórmula para $\\beta_1$:\n\n$$\n\\hat{\\beta}_1 = \\frac{\\sum x_iy_i-\\frac{\\sum x_i \\sum y_i}{n}}{\\sum x_i^2 - \\frac{(\\sum x_i)^2}{n}}\n$$\n\n$$\n\\hat{\\beta}_0 = \\bar{y} - \\beta_1\\bar{x}\n$$\n\nEl método de los mínimos cuadrados fue creado por *Johann Carl Friedrich Gauss* (1777-1855). Tiene además la ventaja que el promedio de los errores residuales = 0 y que para cada estimación, la varianza del error es mínima.\n\n**Test de hipótesis para** $\\beta_1$ e Intervalo de Confianza 95%\n\nComo siempre que trabajamos con una muestra, será necesario aplicar los procesos de inferencia. Es por eso que los softwares ofrecen un test de hipótesis para el coeficiente.\n\nLa hipótesis nula podría entenderse como que $x$ no logra explicar la variación de $y$ (entonces la pendiente de la recta sería nula)\n\n$$\nH_0: \\beta_1 = 0\n$$\n\nAl calcular el modelo de regresión, todos los *software* estiman el coeficiente y el error estándar del mismo ($SE$) y testean el coeficiente.\n\n**Bondad de ajuste**\n\nHasta ahora hemos aprendido a explicar la variación de $y$ según la variación de $x$ mediante un modelo en donde las desviaciones entre el valor observado (“real”) y el estimado (“modelo de regresión”) son las menores posibles.\n\nAhora debemos saber, según los datos que tenemos, cuán bueno es el modelo que ajustamos (qué capacidad tiene de explicar la variabilidad de $y$ o, si lo quiero utilizar para realizar una predicción, cuánto se alejará mi valor estimado del verdadero, “real” valor de $y$). Esta evaluación la realizaremos mediante la descomposición de la varianza del modelo. Por definición la varianza o variabilidad total es la sumatoria de la diferencia entre cada valor de $y$ con el promedio de $y$ (elevado al cuadrado ya que hay valores negativos y positivos que si los sumamos se anularían).\n\nLa variabilidad total del modelo es la suma entre la variabilidad que logró explicar la regresión y la variabilidad residual.\n\n$$\n\\sum (y_i-\\bar{y})^2 = \\sum (\\hat{y}-\\bar{y})^2 + \\sum (y_i -\\hat{y}_i)^2 \n$$\n\n$$\\frac{Suma \\; de \\; cuadrados}{totales \\; (SCT)} \\; \\frac{Suma \\; de \\; cuadrados}{de \\; la \\; regresion \\; (SCR)} \\; \\frac{Suma \\; de \\; cuadrados}{residuales \\; (SCE)}$$\n\nCuanto mayor sea la variabilidad que logre explicar la regresión en relación a los residuos, tanto mejor será el modelo. Este es el fundamento para el cálculo del coeficiente de determinación ($R^2$)\n\n$$\nR^2 = \\frac{SCR}{SCT} = 1 - \\frac{SCE}{SCT}\n$$\n\n$R^2$ expresa la proporción de la variación total que logra explicar el modelo de regresión. Su valor oscila entre 0 y 1, es una cantidad adimensional.\n\n- Cuando el ajuste es bueno $R^2$ será cercano a 1, cuando el ajuste es malo $R^2$ será cercano a 0.\n\n- En la Regresión lineal simple el coeficiente de determinación ($R^2$) es igual al $r$ de Pearson elevado al cuadrado.\n\nPara visualizar simulaciones al respecto pueden visitar el siguiente enlace:\n\n➡️[**Viendo la teoría. Una introducción visual a probabilidad y estadística**](https://seeing-theory.brown.edu/regression-analysis/es.html#section1)\n\n## Ejemplo práctico en R\n\nPara llevar a cabo el análisis en R y presentar las funciones y paquetes que nos pueden ayudar en la tarea vamos a trabajar con el set de datos `cancer_USA.txt` que utilizamos para el ejemplo de [covarianza y correlación](03_covarianza_correlacion.qmd).\n\nComenzaremos por cargar los paquetes necesarios para el análisis:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Tablas de coeficientes\nlibrary(gtsummary)\n\n# Chequeo de supuestos\nlibrary(easystats)\nlibrary(lmtest)\nlibrary(nortest)\n\n# Paletas aptas daltonismo\nlibrary(scico)\n\n# Manejo de datos\nlibrary(tidyverse)\n```\n:::\n\n\nCargamos los datos y revisamos la estructura de la tabla:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Carga datos\ndatos <- read_csv2(\"datos/cancer_USA.txt\")\n\n# Explora datos\nglimpse(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 213\nColumns: 10\n$ condado            <chr> \"Belknap County\", \"Carroll County\", \"Cheshire Count…\n$ estado             <chr> \"New Hampshire\", \"New Hampshire\", \"New Hampshire\", …\n$ tasa_mortalidad    <dbl> 182.6, 168.8, 162.8, 181.6, 155.0, 163.2, 173.1, 17…\n$ mediana_edad       <dbl> 46.1, 50.3, 42.0, 48.1, 41.9, 40.1, 42.6, 43.5, 37.…\n$ mediana_edad_cat   <chr> \"45+ años\", \"45+ años\", \"36-39 años\", \"45+ años\", \"…\n$ mediana_ingresos   <dbl> 59831, 57556, 56008, 42491, 56353, 71233, 62429, 79…\n$ pct_pobreza        <dbl> 10.0, 10.7, 11.8, 14.9, 11.6, 8.7, 9.5, 6.1, 11.8, …\n$ pct_salud_publica  <dbl> 16.8, 13.4, 12.7, 22.5, 14.0, 12.7, 13.1, 9.0, 12.4…\n$ pct_sec_incompleta <dbl> 15.4, 14.8, 6.1, 13.2, 6.6, 12.9, 10.9, 13.5, 6.1, …\n$ pct_desempleo      <dbl> 5.3, 5.8, 6.1, 6.9, 5.0, 5.9, 5.2, 5.6, 6.5, 5.8, 1…\n```\n\n\n:::\n:::\n\n\nRecordemos que la base de datos tiene 213 observaciones y 10 variables y la variable dependiente es `tasa_mortalidad`. Para ejemplificar los pasos de una regresión lineal simple, evaluaremos la asociación entre la variable dependiente y `mediana_ingresos`.\n\n### Presupuestos\n\nPara que un modelo lineal sea válido, debe cumplir con cuatro supuestos fundamentales: **independencia, linealidad, homocedasticidad y normalidad**. Aunque la verificación rigurosa de estos criterios suele realizarse a partir del análisis de residuos tras ajustar el modelo, es recomendable realizar una evaluación preliminar de los datos para identificar posibles problemas desde el inicio.\n\nLa **independencia** (o ausencia de autocorrelación) puede determinarse, en gran medida, a partir del conocimiento sobre la fuente de los datos y su método de recolección. Sin embargo, siempre es recomendable verificarla en los residuales del modelo.\n\nLa **linealidad** se refiere a la relación entre las variables `tasa_mortalidad` y `mediana_ingresos`. Para comprobarla, se puede utilizar un diagrama de dispersión:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n\n  ggplot(mapping = aes(x = mediana_ingresos, y = tasa_mortalidad)) +\n\n  # gráfico de dispersión\n  geom_point(color = \"#502345\") +\n\n  # tema\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-3-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nObservamos en el gráfico una clara relación inversa entre las variables, dado que los condados donde las personas tienen mayores ingresos la mortalidad por cáncer es menor y viceversa. Podemos dibujar la recta de regresión lineal sobre el diagrama de dispersión adicionando una capa más al gráfico mediante `geom_smooth()` e indicando `method = \"lm\"` como método. Además de la recta se puede ver el intervalo de confianza (zona gris alrededor de ella).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n  ggplot(mapping = aes(x = mediana_ingresos, y = tasa_mortalidad)) +\n\n  # diagrama de dispersión\n  geom_point(color = \"#502345\") +\n\n  # añade línea de regresión\n  geom_smooth(method = \"lm\", color = \"#1B0D33\") +\n\n  # cambia color de fondo\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-4-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nUsaremos la función `cor()` para estimar la correlación entre las dos variables:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(datos$mediana_ingresos, datos$tasa_mortalidad, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5041398\n```\n\n\n:::\n:::\n\n\nEl valor es negativo, lo que confirma lo observado en la nube de puntos anterior. Para poder descartar que esta **correlación negativa** se debe al azar, debemos calcular su significancia:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(datos$mediana_ingresos, datos$tasa_mortalidad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  datos$mediana_ingresos and datos$tasa_mortalidad\nt = -8.4795, df = 211, p-value = 3.938e-15\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.5980408 -0.3965857\nsample estimates:\n       cor \n-0.5041398 \n```\n\n\n:::\n:::\n\n\nEn este ejemplo $p<0,05$, por lo tanto la correlación es significativa.\n\nLa **homocedasticidad** implica que la varianza de los residuos se mantiene aproximadamente constante a lo largo de los valores de la variable independiente. Se puede evaluar gráficamente mediante la dispersión de los residuos respecto a los valores ajustados o a través de contrastes de hipótesis, como el **test de Breusch-Pagan**.\n\nFinalmente, la **normalidad** de los residuos se puede evaluar mediante el **test de Lilliefors**, disponible en el paquete `nortest` [@nortest]:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlillie.test(datos$tasa_mortalidad)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  datos$tasa_mortalidad\nD = 0.042152, p-value = 0.4707\n```\n\n\n:::\n:::\n\n\nTambién se puede verificar gráficamente con un **QQ plot**:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n  ggplot(mapping = aes(sample = tasa_mortalidad)) +\n\n  # añade qqplot\n  stat_qq() +\n  stat_qq_line() +\n\n  # cambia nombres de los ejes X e Y\n  labs(title = \"QQplot\", x = \"Theoretical Quantiles\", y = \"Sample Quantiles\") +\n\n  # modifico color de fondo\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-8-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nTanto el test de hipótesis como los gráficos de cuantiles nos informan que las distribuciones de la variable dependiente cumple con el criterio de \"normalidad\".\n\n### Ajuste del modelo\n\nComo vimos [**anteriormente**](02_mod_estadistico.qmd), la función `lm()` del paquete `stats` nos permite ajustar modelos de regresión lineal:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(tasa_mortalidad ~ mediana_ingresos, data = datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tasa_mortalidad ~ mediana_ingresos, data = datos)\n\nCoefficients:\n     (Intercept)  mediana_ingresos  \n       201.41284          -0.00052  \n```\n\n\n:::\n:::\n\n\nEn este caso, `Intercept` representa el valor de `mediana_ingresos` cuando `tasa_mortalidad` vale cero (ordenada al origen) y el coeficiente de `mediana_ingresos` representa la pendiente de la recta.\n\nEstos resultados obtenidos y aplicados en la fórmula del modelo simple quedarían así:\n\n$$\\operatorname{tasa mortalidad} = \\alpha + \\beta_{1}(\\operatorname{mediana ingresos}) + \\epsilon$$\n\n$$\\operatorname{tasa mortalidad} = 201.4128 + -0.0005*\\operatorname{mediana ingresos} + \\epsilon$$\n\nGuardamos el modelo como un objeto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelo <- lm(tasa_mortalidad ~ mediana_ingresos, data = datos)\n```\n:::\n\n\nPodemos acceder a la salida del modelo mediante la función `summary()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tasa_mortalidad ~ mediana_ingresos, data = datos)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-33.040  -8.210   1.093   7.637  35.932 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       2.014e+02  3.521e+00  57.200  < 2e-16 ***\nmediana_ingresos -5.200e-04  6.133e-05  -8.479 3.94e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 12.32 on 211 degrees of freedom\nMultiple R-squared:  0.2542,\tAdjusted R-squared:  0.2506 \nF-statistic:  71.9 on 1 and 211 DF,  p-value: 3.938e-15\n```\n\n\n:::\n:::\n\n\nLa asociación entre la tasa de mortalidad por cáncer y la mediana de ingresos es estadísticamente significativa ($p < 0.001$).\n\nTodos los ajustes de modelos lineales que produce la función `lm()` tienen la forma de una lista.La manera de conocer su clase es `class()` y su estructura mediante `str()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclass(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"lm\"\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 12\n $ coefficients : Named num [1:2] 201.41284 -0.00052\n  ..- attr(*, \"names\")= chr [1:2] \"(Intercept)\" \"mediana_ingresos\"\n $ residuals    : Named num [1:213] 12.3 -2.68 -9.49 2.28 -17.11 ...\n  ..- attr(*, \"names\")= chr [1:213] \"1\" \"2\" \"3\" \"4\" ...\n $ effects      : Named num [1:213] -2516.47 104.46 -10.27 1.26 -17.89 ...\n  ..- attr(*, \"names\")= chr [1:213] \"(Intercept)\" \"mediana_ingresos\" \"\" \"\" ...\n $ rank         : int 2\n $ fitted.values: Named num [1:213] 170 171 172 179 172 ...\n  ..- attr(*, \"names\")= chr [1:213] \"1\" \"2\" \"3\" \"4\" ...\n $ assign       : int [1:2] 0 1\n $ qr           :List of 5\n  ..$ qr   : num [1:213, 1:2] -14.5945 0.0685 0.0685 0.0685 0.0685 ...\n  .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. ..$ : chr [1:213] \"1\" \"2\" \"3\" \"4\" ...\n  .. .. ..$ : chr [1:2] \"(Intercept)\" \"mediana_ingresos\"\n  .. ..- attr(*, \"assign\")= int [1:2] 0 1\n  ..$ qraux: num [1:2] 1.07 1.01\n  ..$ pivot: int [1:2] 1 2\n  ..$ tol  : num 1e-07\n  ..$ rank : int 2\n  ..- attr(*, \"class\")= chr \"qr\"\n $ df.residual  : int 211\n $ xlevels      : Named list()\n $ call         : language lm(formula = tasa_mortalidad ~ mediana_ingresos, data = datos)\n $ terms        :Classes 'terms', 'formula'  language tasa_mortalidad ~ mediana_ingresos\n  .. ..- attr(*, \"variables\")= language list(tasa_mortalidad, mediana_ingresos)\n  .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. ..$ : chr [1:2] \"tasa_mortalidad\" \"mediana_ingresos\"\n  .. .. .. ..$ : chr \"mediana_ingresos\"\n  .. ..- attr(*, \"term.labels\")= chr \"mediana_ingresos\"\n  .. ..- attr(*, \"order\")= int 1\n  .. ..- attr(*, \"intercept\")= int 1\n  .. ..- attr(*, \"response\")= int 1\n  .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. ..- attr(*, \"predvars\")= language list(tasa_mortalidad, mediana_ingresos)\n  .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. ..- attr(*, \"names\")= chr [1:2] \"tasa_mortalidad\" \"mediana_ingresos\"\n $ model        :'data.frame':\t213 obs. of  2 variables:\n  ..$ tasa_mortalidad : num [1:213] 183 169 163 182 155 ...\n  ..$ mediana_ingresos: num [1:213] 59831 57556 56008 42491 56353 ...\n  ..- attr(*, \"terms\")=Classes 'terms', 'formula'  language tasa_mortalidad ~ mediana_ingresos\n  .. .. ..- attr(*, \"variables\")= language list(tasa_mortalidad, mediana_ingresos)\n  .. .. ..- attr(*, \"factors\")= int [1:2, 1] 0 1\n  .. .. .. ..- attr(*, \"dimnames\")=List of 2\n  .. .. .. .. ..$ : chr [1:2] \"tasa_mortalidad\" \"mediana_ingresos\"\n  .. .. .. .. ..$ : chr \"mediana_ingresos\"\n  .. .. ..- attr(*, \"term.labels\")= chr \"mediana_ingresos\"\n  .. .. ..- attr(*, \"order\")= int 1\n  .. .. ..- attr(*, \"intercept\")= int 1\n  .. .. ..- attr(*, \"response\")= int 1\n  .. .. ..- attr(*, \".Environment\")=<environment: R_GlobalEnv> \n  .. .. ..- attr(*, \"predvars\")= language list(tasa_mortalidad, mediana_ingresos)\n  .. .. ..- attr(*, \"dataClasses\")= Named chr [1:2] \"numeric\" \"numeric\"\n  .. .. .. ..- attr(*, \"names\")= chr [1:2] \"tasa_mortalidad\" \"mediana_ingresos\"\n - attr(*, \"class\")= chr \"lm\"\n```\n\n\n:::\n:::\n\n\nLa función `tbl_regression()` del paquete `gtsummary` [@gtsummary], nos permite generar una tabla con los coeficientes del modelo. El nivel de confianza puede ajustarse con el argumento `conf.level` y el argumento `intercept` muestra u oculta el intercepto:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntbl_regression(modelo, intercept = T, conf.level = .95)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"osncjrvket\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#osncjrvket table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#osncjrvket thead, #osncjrvket tbody, #osncjrvket tfoot, #osncjrvket tr, #osncjrvket td, #osncjrvket th {\n  border-style: none;\n}\n\n#osncjrvket p {\n  margin: 0;\n  padding: 0;\n}\n\n#osncjrvket .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#osncjrvket .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#osncjrvket .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#osncjrvket .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#osncjrvket .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#osncjrvket .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#osncjrvket .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#osncjrvket .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#osncjrvket .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#osncjrvket .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#osncjrvket .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#osncjrvket .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#osncjrvket .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#osncjrvket .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#osncjrvket .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#osncjrvket .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#osncjrvket .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#osncjrvket .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#osncjrvket .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#osncjrvket .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#osncjrvket .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#osncjrvket .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#osncjrvket .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#osncjrvket .gt_left {\n  text-align: left;\n}\n\n#osncjrvket .gt_center {\n  text-align: center;\n}\n\n#osncjrvket .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#osncjrvket .gt_font_normal {\n  font-weight: normal;\n}\n\n#osncjrvket .gt_font_bold {\n  font-weight: bold;\n}\n\n#osncjrvket .gt_font_italic {\n  font-style: italic;\n}\n\n#osncjrvket .gt_super {\n  font-size: 65%;\n}\n\n#osncjrvket .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#osncjrvket .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#osncjrvket .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#osncjrvket .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#osncjrvket .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#osncjrvket .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#osncjrvket .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#osncjrvket .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#osncjrvket div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">201</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">194, 208</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">mediana_ingresos</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.00, 0.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Residuales\n\nEl **residuo** o **residual** de una estimación se define como la diferencia entre el valor observado y el valor predicho por el modelo de regresión. Son fundamentales para evaluar la bondad de ajuste y verificar los supuestos básicos de los modelos lineales. Para resumir el conjunto de residuales, se pueden emplear dos enfoques:\n\n1.  La **sumatoria del valor absoluto** de cada residual.\n\n2.  La **sumatoria del cuadrado** de cada residual (**RSS,** *Residual Sum of Squares*), basada en el método de los mínimos cuadrados, amplifica las desviaciones extremas y permite minimizar errores en la estimación de parámetros.\n\nLos residuales se almacenan en el objeto de regresión y pueden visualizarse mediante:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresid(modelo)\n```\n:::\n\n\nCuanto mayor sea la **sumatoria de los cuadrados de los residuales**, menor será la precisión con la que el modelo predice el valor de la variable dependiente a partir de la variable predictora.\n\nUn análisis gráfico resulta muy útil para evaluar los supuestos del modelo. Aplicando la función `plot()` al objeto de regresión:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(modelo)\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nEsta función genera cuatro gráficos automáticos:\n\n- `Residuals vs Fitted`**:** Permite evaluar la **linealidad**. La línea roja debería ser lo más horizontal posible y sin curvaturas pronunciadas. Si hay curvatura, podría indicar la necesidad de un término no lineal (cuadrático, logarítmico, etc.) o la omisión de una variable importante en el modelo.\n\n- `Normal Q-Q`**:** Evalúa la **normalidad** de los residuos. Los puntos deberían ajustarse a la diagonal. Desviaciones importantes sugieren un incumplimiento del supuesto de normalidad.\n\n- `Scale-Location`**:** Indica si los residuos se distribuyen uniformemente a lo largo del rango de los predictores, verificando la **homocedasticidad**. Una línea aproximadamente horizontal con puntos dispersos de manera aleatoria es una buena señal.\n\n- `Residuals vs Leverage`**:** Ayuda a identificar **valores influyentes**. Un punto extremo no necesariamente es influyente, pero aquellos fuera de las líneas rojas punteadas (altas puntuaciones de distancia de Cook) pueden estar afectando considerablemente el modelo.\n\nOtra opción para evaluar gráficamente los supuestos del modelo es la función `check_model()` del paquete `performance` , el cual forma parte del ecosistema `easystats` [@easystats]:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(modelo)\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-16-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nPodemos elegir que gráficos visualizar usando el argumento `check`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(\n  modelo,\n  check = c(\"normality\", \"qq\", \"linearity\", \"homogeneity\", \"outliers\")\n)\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-17-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nPara evaluar la linealidad se puede aplicar el test RESET de Ramsey, mediante la función `resettest()` del paquete `lmtest` [@lmtest]:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresettest(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tRESET test\n\ndata:  modelo\nRESET = 0.82653, df1 = 2, df2 = 209, p-value = 0.439\n```\n\n\n:::\n:::\n\n\nLa hipótesis nula indica que las variables se relacionan de forma lineal; un $p<0,05$ sugiere lo contrario. En nuestro modelo, el valor *p* de 0.439 respalda la suposición de linealidad.\n\nOtro supuesto fundamental es que los residuales deben distribuirse de forma normal (con media 0). Además del QQ-plot, se puede aplicar el test de Lilliefors:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlillie.test(modelo$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  modelo$residuals\nD = 0.05804, p-value = 0.07821\n```\n\n\n:::\n:::\n\n\nCon un *p*-valor de 0.078 se confirma la normalidad.\n\nEl test de Breusch-Pagan, implementado en `lmtest` y `performance`, evalúa si la varianza de los residuos es constante. Parte de la hipótesis nula de **homocedasticidad** o varianza constante en las perturbaciones y la enfrenta a la alternativa de varianza variable, por lo que es válido decir que cumple con el supuesto de homocedasticidad si el valor $p>0,05$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# paquete lmtest\nbptest(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  modelo\nBP = 2.5078, df = 1, p-value = 0.1133\n```\n\n\n:::\n\n```{.r .cell-code}\n# paquete performance\ncheck_heteroscedasticity(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.087).\n```\n\n\n:::\n:::\n\n\nIncluso cuando el modelo cumple todos los supuestos, es importante identificar observaciones atípicas o de alto *leverage*, ya que podrían condicionar el ajuste. Los valores atípicos u *outliers* son observaciones que no se ajustan bien al modelo, con residuos excesivamente grandes. Por otro lado, los puntos con alto *leverage* tienen valores extremos en los predictores, lo que los hace potencialmente influyentes.\n\nPara ello se pueden analizar los residuales estandarizados y los residuales estudentizados. Los **residuales estandarizados** se obtienen normalizando los residuales por su desviación estándar. Esta aproximación permite identificar valores atípicos que se alejan más de $\\pm3$ desviaciones estándar. Sin embargo, si un *outlier* influye lo suficiente en el modelo como para atraer la línea de regresión, su residual podría ser pequeño y pasar desapercibido. Una alternativa más robusta es utilizar los **residuales estudentizados**. Se trata de un proceso iterativo en el que se va excluyendo cada vez una observación $i$ distinta y se reajusta el modelo con las $n-1$ restantes. En cada proceso de exclusión y reajuste se calcula la diferencia ($d_i$) entre el valor predicho para $i$ habiendo y sin haber excluido esa observación. Finalmente, se normalizan las diferencias $d_i$ . Aquellos valores $d_i$ cuyo residual estudentizado supera $\\pm 3$ suelen considerarse significativos.\n\nEstos dos procesos sobre los residuales se pueden calcular en R mediante las funciones `rstandar()` y `rstudent()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creación del dataset de residuales\nresiduales <- tibble(\n  residuales = residuals(modelo),\n  resid_normalizados = rstandard(modelo),\n  resid_estudentizados = rstudent(modelo)\n)\n```\n:::\n\n\nPodemos visualizar la comparación de estos residuales mediante un *boxplot* usando *facets*:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresiduales |>\n\n  # Pasa a formato long\n  pivot_longer(cols = everything(), names_to = \"tipo\") |>\n\n  # Genera gráfico\n  ggplot(mapping = aes(y = value, fill = tipo)) +\n\n  geom_boxplot() +\n\n  scale_fill_scico_d() +\n\n  facet_wrap(~tipo, scales = \"free_y\") + # subdivide en facets\n\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-22-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nSi encontramos residuales con valores absolutos superiores a 3 en el gráfico de residuales estudentizados, es recomendable investigarlos más a fondo. Podemos identificarlos con:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(rstudent(modelo) > 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE \n  213 \n```\n\n\n:::\n:::\n\n\nPara evaluar la influencia de observaciones, se utiliza la **distancia de Cook**, que combina la magnitud del residual y el *leverage*. Valores superiores a 1 se consideran generalmente influyentes. Esto se puede visualizar mediante:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(modelo, which = 5)\n```\n\n::: {.cell-output-display}\n![](04_reg_lineal_files/figure-html/ej-24-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nAl observar el gráfico, se debe prestar especial atención a los puntos situados en las esquinas superior e inferior, es decir, aquellos que aparecen fuera de las líneas discontinuas rojas. Estos puntos suelen presentar altas puntuaciones en la distancia de Cook, lo que indica que pueden influir significativamente en los resultados de la regresión.\n\nAdemás, el paquete `performance` incluye la función `check_outliers()` para detectar valores atípicos según su distancia de Cook:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_outliers(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: No outliers detected.\n- Based on the following method and threshold: cook (0.7).\n- For variable: (Whole model)\n```\n\n\n:::\n:::\n\n\nEn el ejemplo analizado, no se identificaron valores influyentes evidentes. Sin embargo, si se detecta alguna observación fuera de estos límites, es recomendable estudiarla de forma individual para determinar, por ejemplo, si su elevada influencia se debe a un error de registro. En tal caso podremos eliminar la observación (o corregirla) y analizar los casos restantes. Pero si el dato es correcto, quizás sea diferente de las otras observaciones y encontrar las causas de este fenómeno puede llegar a ser la parte más interesante del análisis. Por supuesto que todo esto dependerá del contexto del problema que uno esta estudiando.\n\n### Bondad de ajuste del modelo\n\nUna vez ajustado un modelo, es necesario verificar su eficiencia, ya que, aun siendo la línea que mejor se ajusta a las observaciones entre todas las posibles, el modelo puede resultar inadecuado. Entre las medidas más utilizadas para evaluar la calidad del ajuste se encuentran el error estándar de los residuales, el test $F$ y el coeficiente de determinación $R^2$. Estos valores aparecen al final de la salida de la función `summary()`, donde se pueden identificar el RSE (*Residual Standard Error*), el $R^2$ (*Multiple R-squared*) y el $R^2$ ajustado (*Adjusted R-squared*).\n\nPodemos acceder al valor de $R^2$ del modelo usando la función `r2()` del paquete `performance`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr2(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.254\n  adj. R2: 0.251\n```\n\n\n:::\n:::\n\n\nEl $R^2$ oscila entre 0 y 1, de modo que valores cercanos a 1 indican un buen ajuste del modelo lineal a los datos. Por otro lado, el $R^2$ ajustado penaliza la inclusión de variables independientes poco relevantes en la explicación de la variable dependiente, razón por la cual su valor es menor o igual al $R^2$. En nuestro ejemplo los valores de $R^2$ obtenidos nos indican que el modelo lineal simple no se ajusta demasiado bien a los datos. Esto significa que solamente un 25.1 % de la variación en la tasa de mortalidad por cáncer se explica únicamente por la mediana de ingresos como variable explicativa; el restante 74.9 % no se explica, lo que sugiere que agregar otras variables independientes podría mejorar el ajuste y, por ende, la confiabilidad de las predicciones.\n\nLa salida de `summary()` también incluye un estadístico $F$ de Snedecor y su $p$*-*valor correspondiente, que se utilizan en el contraste ómnibus para evaluar, de forma global, la idoneidad del modelo. En nuestro ejemplo, $p>0,05$, por lo que, al 95 % de confianza, se rechaza la hipótesis nula y se concluye que el modelo lineal es adecuado para el conjunto de datos. Cabe mencionar que, cuando el modelo de regresión tiene una única variable explicativa, este contraste es equivalente al contraste del parámetro $\\beta_1​$.\n\nOtra forma de verificar de manera independiente la significación del modelo es mediante la función `anova()`, que plantea el contraste de la regresión mediante el [**análisis de la varianza**](05_anova.qmd):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: tasa_mortalidad\n                  Df Sum Sq Mean Sq F value    Pr(>F)    \nmediana_ingresos   1  10912 10911.8  71.901 3.938e-15 ***\nResiduals        211  32021   151.8                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nLa tabla de análisis de varianza muestra resultados coherentes con el bloque final de `summary(modelo)`, presentando un valor $F$ de 71.9 y un $p$-valor significativo.\n\n### Interpretación de resultados\n\nSe realizó una regresión lineal simple para analizar la relación entre la mediana de ingresos y la tasa de mortalidad por cáncer en 174 condados de la Costa Este de Estados Unidos. El diagrama de dispersión mostró una relación lineal negativa moderada entre ambas variables, lo que se confirmó con un coeficiente de correlación de Pearson de\\\n-0.5. Además, el análisis de regresión reveló que la relación es estadísticamente significativa (t = -8.48, *p* = 0).\n\nEl coeficiente de pendiente para la mediana de ingresos fue de\\\n0, lo que indica que, por cada unidad de incremento en la mediana de ingresos, la tasa de mortalidad por cáncer disminuye aproximadamente en 0,05 puntos porcentuales. El $R^2$ del modelo muestra que el 25.1 % de la variación en la tasa de mortalidad se explica únicamente con esta variable, lo que sugiere la existencia de otros factores que también influyen en la mortalidad por cáncer.\n\nFinalmente, la gráfica de dispersión de los valores pronosticados estandarizados frente a los residuos estandarizados evidenció que se cumplen los supuestos de homogeneidad de varianza y linealidad, y que los residuos se distribuyen de forma aproximadamente normal. Se cumplieron todos los presupuestos necesarios para validar la regresión y no se encontraron valores atípicos influyentes.\n\n::: hidden\n@ballesterdíez2003\n\n@daniel2002\n\n@hernández-hernández-ávila2011\n\n@weisberg2005\n\n@zeileis2002\n\n@base\n\n@wickham2019\n\n@royo-bordonada2009\n\n@schloerke2010\n:::\n\n## Referencias {.unnumbered}\n",
    "supporting": [
      "04_reg_lineal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}