project:
  type: book  

book:
  ## Metadatos
  title: "Epidemiología: Nivel Avanzado"
  author: "Instituto Nacional de Epidemiología 'Dr. J. H. Jara'"
  page-footer: 
    center: Este material es parte del curso de Epidemiología - Nivel Avanzado © 2025 Instituto Nacional de Epidemiología "Dr. Juan H. Jara" (ANLIS)
  output-file: "epi_avanzada"

  ## Barra Navegación  
  navbar: 
    background: "#2F2E4E"
    logo: logos/logos_ine.svg
    search: true
    pinned: true
    right: 
      - text: "Descargas"
        icon: cloud-download
        menu: 
          - text: "Material en PDF"
            icon: file-earmark-pdf
            href: epi_avanzada.pdf
          - text: "Material en EPUB"
            icon: book
            href: epi_avanzada.epub
          - text: "R para Windows"
            icon: windows
            target: _blank
            href: https://cran.rstudio.com/bin/windows/
          - text: "R para macOS"
            icon: apple
            target: _blank
            href: https://cran.rstudio.com/bin/macosx/
          - text: "R para Linux"
            icon: ubuntu
            target: _blank
            href: https://cran.rstudio.com/bin/linux/
          - text: "RStudio Desktop"
            icon: terminal
            target: _blank
            href: https://posit.co/download/rstudio-desktop/
          - text: "RTools"
            icon: terminal
            target: _blank
            href: https://cran.r-project.org/bin/windows/Rtools/
          - text: "Paquetes para el curso y datos de ejemplo"
            icon: file-zip
            href: files/datos_y_paquetes.zip
          
          
  sidebar: 
    logo: logos/logo_curso.png 
            
  ## Capítulos
  chapters:
    - text: "Prefacio"
      icon: book
      href: index.qmd
    - part: "Unidad 1"
      icon: file-earmark-bar-graph
      chapters: 
        - "unidad_1/01_intro_R.qmd"
        - "unidad_1/02_intro_RStudio.qmd"
        - "unidad_1/03_intro_tidyverse.qmd"
        - "unidad_1/04_intro_dplyr.qmd"
        - "unidad_1/05_intro_ggplot.qmd"
        - "unidad_1/06_analisis_exploratorio.qmd"
        - "unidad_1/07_hoja_estilo.qmd"
    # - part: "Unidad 2"
    #   icon: file-earmark-bar-graph
    #   chapters: 
    #     - "unidad_2/01_est_epidemiologicos.qmd"
    #     - "unidad_2/02_est_transversales.qmd"
    #     - "unidad_2/03_inferencia.qmd"
    #     - "unidad_2/04_normalidad_heterocedasticidad.qmd"
    #     - "unidad_2/05_muestreo.qmd"
    #     - "unidad_2/06_fun_condicionales.qmd"
    #     - "unidad_2/07_IC_complejos.qmd"
    # - part: "Unidad 3"
    #   icon: file-earmark-bar-graph
    #   chapters: 
    #     - "unidad_3/01_est_ecologicos.qmd"
    #     - "unidad_3/02_mod_estadistico.qmd" 
    #     - "unidad_3/03_covarianza_correlacion.qmd" 
    #     - "unidad_3/04_reg_lineal.qmd" 
    #     - "unidad_3/05_anova.qmd"
    #     - "unidad_3/06_rol_variables.qmd"  
    #     - "unidad_3/07_reg_lineal_multiple.qmd"
    # - part: "Unidad 4"
    #   icon: file-earmark-bar-graph
    #   chapters: 
    #     - "unidad_4/01_est_caso_control.qmd"
    #     - "unidad_4/02_reg_logistica.qmd"
    #     - "unidad_4/03_sep_datos.qmd"
    #     - "unidad_4/04_reg_logistica_cond.qmd" 
    #     - "unidad_4/05_mod_predict.qmd" 
    # - part: "Unidad 5"
    #   icon: file-earmark-bar-graph
    #   chapters: 
    #     - "unidad_5/01_est_cohortes.qmd" 
    #     - "unidad_5/02_reg_poisson.qmd"  
    #     - "unidad_5/03_dispersion.qmd" 
    # - part: "Unidad 6"
    #   icon: file-earmark-bar-graph
    #   chapters:
    #     - "unidad_6/01_est_experimentales.qmd"   
    #     - "unidad_6/02_analisis_superv.qmd"
    #     - "unidad_6/03_metodos_analisis_sup.qmd"
    #     - "unidad_6/04_reg_cox.qmd"


## Botón de anterior/siguiente
page-navigation: true
  
## Botón de volver arriba
back-to-top-navigation: true

## Números de sección
number-sections: true
number-depth: 2

## Opciones de formato
format:
  html:
    # Tema claro y oscuro
    theme: 
     light: cosmo
     dark: cyborg
     
     # Botón para cambiar a modo oscuro
    include-in-header:
      text: |
        <style type="text/css">
        .quarto-reader-toggle .bi::before, .quarto-color-scheme-toggle .bi::before {
          display: inline-block;
          height: 40px;
          width: 40px;
          background-size: 20px 20px;
          background-position: center;
          background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="rgba(189, 195, 199, 1)" class="bi bi-moon-stars-fill" viewBox="0 0 16 16"> <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278"/> <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.73 1.73 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.73 1.73 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.73 1.73 0 0 0 1.097-1.097zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/> </svg>') !important;
        }
        </style>
        
    # CSS
    css: styles.css
    
    # Tabla de contenidos
    toc: true
    toc-title: "Contenidos"    

  epub:
    cover-image: logos/logo_curso.png

  pdf: 
    documentclass: book
    papersize: a4
    geometry:
      - top=20mm
      - left=20mm

# Tipografía
mainfont: "Calibri"

# Archivos para descargar
resources: 
  - files/
  
# Idioma del documento
lang: es

# Salida código de R
execute: 
  echo: true
  warning: false
  freeze: auto
  
# Metadatos
license: CC BY-NC

# Autores
author: 
  - name: Christian Ballejo
    orcid: 0000-0002-7346-5701
  - name: Andrea Silva
    orcid: 0000-0002-4791-9706
  - name: Tamara Ricardo
    orcid: 0000-0002-0921-2611  
