{
  "hash": "b9d8a0ee7d0f45a3355bc59c7611e01a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis de la varianza (ANOVA)\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Introducción\n\nEl análisis de varianza (ANOVA) es una extensión del modelo lineal general que se utiliza para comparar las medias de una variable dependiente continua ($Y$) entre diferentes niveles de una variable explicativa categórica ($X$), que debe tener al menos tres niveles.\n\nLa hipótesis nula ($H_0$) del test estadístico establece que las medias de la variable dependiente son iguales en todos los grupos, mientras que la hipótesis alternativa ($H_1$) plantea que al menos dos medias difieren significativamente:\n\n-   $H_0: \\mu_1 = \\mu_2 = ... = \\mu_i$\n\n-   $H_1$: al menos una $\\mu_i \\not= \\mu_j$\n\nPor lo tanto, el ANOVA permite comparar múltiples medias, pero lo hace analizando la variabilidad entre y dentro de los grupos.\n\nLa variabilidad total se descompone en dos componentes:\n\n-   **Intervarianza (SSB):** Variabilidad entre los grupos.\n\n-   **Intravarianza (SSE):** Variabilidad dentro de los grupos.\n\nEl estadístico $F$ del ANOVA, que sigue una distribución F de Fisher-Snedecor, compara estas dos fuentes de variabilidad:\n\n$$\nF = \\frac{SSB/(k-1)}{SSE/(n-k)}\n$$\n\ndonde:\n\n-   $k$: el número de grupos.\n\n-   $n$: número total de observaciones.\n\nSi se cumple $H_0$, el estadístico $F$ tiende a 1, ya que las varianzas entre y dentro de los grupos son similares. Si las medias difieren significativamente, la intervarianza será mayor que la intravarianza, resultando en valores de $F$ superiores a 1.\n\n## ANOVA de un factor o de una vía\n\nEl ANOVA de una vía puede considerare como una extensión de los *t-test* independientes para comparar más de dos grupos de un factor. En este contexto, factor se refiere a la variable categórica que define los grupos.\n\nPara que los resultados del ANOVA sean válidos, deben cumplirse los siguientes supuestos:\n\n-   **Aleatoriedad:** Las observaciones deben ser aleatorias.\n\n-   **Independencia:** Las observaciones entre grupos deben ser independientes.\n\n-   **Variable dependiente:** Cuantitativa continua.\n\n-   **Variable explicativa:** Categórica con más de dos niveles.\n\n-   **Normalidad:** La distribución de la variable dependiente dentro de cada grupo debe ser normal.\n\n-   **Homocedasticidad:** Las varianzas de los grupos deben ser homogéneas.\n\n## Ejemplo práctico en R\n\nNuevamente vamos a trabajar con el conjunto de datos \"`cancer_USA.txt`\", que contiene información sobre la tasa de mortalidad por cáncer (por 100.000 habitantes) en distintos condados de la Costa Este de Estados Unidos. Nuestro objetivo será analizar la relación entre la tasa de mortalidad (`tasa_mortalidad`) y el estado de residencia (`estado`).\n\nComenzaremos por cargar los paquetes necesarios:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# tablas salida del modelo\nlibrary(gtsummary)\n\n# chequeo de supuestos\nlibrary(easystats)\nlibrary(nortest)\nlibrary(pwr)\n\n# comparación de medias\nlibrary(emmeans)\n\n# análisis exploratorio\nlibrary(skimr)\nlibrary(dlookr)\n\n# paletas de colores aptas daltonismo\nlibrary(scico)\n\n# manejo de datos\nlibrary(janitor)\nlibrary(tidyverse)\n```\n:::\n\n\nCargamos y exploramos los datos:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Carga datos\ndatos <- read_csv2(\"datos/cancer_USA.txt\")\n\n# Explora datos\nglimpse(datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 213\nColumns: 10\n$ condado            <chr> \"Belknap County\", \"Carroll County\", \"Cheshire Count…\n$ estado             <chr> \"New Hampshire\", \"New Hampshire\", \"New Hampshire\", …\n$ tasa_mortalidad    <dbl> 182.6, 168.8, 162.8, 181.6, 155.0, 163.2, 173.1, 17…\n$ mediana_edad       <dbl> 46.1, 50.3, 42.0, 48.1, 41.9, 40.1, 42.6, 43.5, 37.…\n$ mediana_edad_cat   <chr> \"45+ años\", \"45+ años\", \"36-39 años\", \"45+ años\", \"…\n$ mediana_ingresos   <dbl> 59831, 57556, 56008, 42491, 56353, 71233, 62429, 79…\n$ pct_pobreza        <dbl> 10.0, 10.7, 11.8, 14.9, 11.6, 8.7, 9.5, 6.1, 11.8, …\n$ pct_salud_publica  <dbl> 16.8, 13.4, 12.7, 22.5, 14.0, 12.7, 13.1, 9.0, 12.4…\n$ pct_sec_incompleta <dbl> 15.4, 14.8, 6.1, 13.2, 6.6, 12.9, 10.9, 13.5, 6.1, …\n$ pct_desempleo      <dbl> 5.3, 5.8, 6.1, 6.9, 5.0, 5.9, 5.2, 5.6, 6.5, 5.8, 1…\n```\n\n\n:::\n:::\n\n\nLa base de datos tiene  observaciones y  variables. La variable dependiente es `tasa_mortalidad`, mientras que `estado` es nuestra variable explicativa, categórica con 9 niveles.\n\nExploremos más en profundidad la estructura de los datos usando la función `skim()` del paquete `skimr`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Resumen de los datos\nskim(datos)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |datos |\n|Number of rows           |213   |\n|Number of columns        |10    |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |3     |\n|numeric                  |7     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: character**\n\n|skim_variable    | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:----------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|condado          |         0|             1|  10|  19|     0|      174|          0|\n|estado           |         0|             1|   5|  13|     0|        9|          0|\n|mediana_edad_cat |         0|             1|   8|  10|     0|        4|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable      | n_missing| complete_rate|     mean|       sd|      p0|     p25|     p50|     p75|     p100|hist  |\n|:------------------|---------:|-------------:|--------:|--------:|-------:|-------:|-------:|-------:|--------:|:-----|\n|tasa_mortalidad    |         0|             1|   172.43|    14.23|   138.8|   162.2|   173.3|   181.6|    216.7|▂▆▇▃▁ |\n|mediana_edad       |         0|             1|    42.06|     3.67|    30.2|    39.9|    42.2|    44.4|     51.9|▁▂▇▅▁ |\n|mediana_ingresos   |         0|             1| 55740.31| 13795.54| 33687.0| 45860.0| 52195.0| 60387.0| 103876.0|▆▇▂▂▁ |\n|pct_pobreza        |         0|             1|    13.25|     3.91|     4.7|    10.7|    13.2|    15.4|     31.5|▃▇▃▁▁ |\n|pct_salud_publica  |         0|             1|    17.86|     4.91|     7.1|    14.6|    17.7|    20.7|     38.2|▃▇▃▁▁ |\n|pct_sec_incompleta |         0|             1|    13.21|     4.76|     3.1|    10.2|    12.7|    15.7|     34.2|▃▇▃▁▁ |\n|pct_desempleo      |         0|             1|     7.50|     1.76|     3.0|     6.4|     7.3|     8.6|     14.0|▂▇▆▁▁ |\n\n\n:::\n\n```{.r .cell-code}\n# Frecuencia por estado\ntabyl(datos$estado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  datos$estado  n    percent\n   Connecticut  8 0.03755869\n         Maine 16 0.07511737\n Massachusetts 14 0.06572770\n New Hampshire 10 0.04694836\n    New Jersey 21 0.09859155\n      New York 62 0.29107981\n  Pennsylvania 64 0.30046948\n  Rhode Island  4 0.01877934\n       Vermont 14 0.06572770\n```\n\n\n:::\n:::\n\n\nObservamos que la variable `estado` tiene 9 niveles y ningún valor ausente (`n_missing = 0`). La variable dependiente tiene valores entre 139 y 217 (casos/100 000 habitantes) y tampoco presenta valores `NA`.\n\nLos estados con menos observaciones (Connecticut, New Hampshire y Rhode Island) serán excluidos para evitar sesgos en el análisis. También convertiremos la variable estado a un factor ordenado con el comando `fct_relevel()` del paquete `tidyverse`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Filtramos estados con pocas observaciones y convertimos a factor\ndatos <- datos |>\n  filter(!estado %in% c(\"New Hampshire\", \"Rhode Island\", \"Connecticut\")) |>\n\n  mutate(estado = fct_relevel(estado, \"New York\", after = 0))\n\n# Verificamos con class() y levels()\nclass(datos$estado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"factor\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(datos$estado)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"New York\"      \"Maine\"         \"Massachusetts\" \"New Jersey\"   \n[5] \"Pennsylvania\"  \"Vermont\"      \n```\n\n\n:::\n:::\n\n\nGraficamos la distribución de la variable dependiente mediante un histograma y un *boxplot*:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# histograma\ndatos |>\n  ggplot(mapping = aes(x = tasa_mortalidad)) +\n  geom_histogram(binwidth = 10, color = \"white\", fill = \"#1E6590\") +\n  theme_minimal() # tema claro\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-5-1.png){fig-align='center' width=85%}\n:::\n\n```{.r .cell-code}\n# boxplot\ndatos |>\n  ggplot(mapping = aes(y = tasa_mortalidad)) +\n  geom_boxplot(fill = \"#B2D680\") +\n  theme_minimal() # tema claro\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-5-2.png){fig-align='center' width=85%}\n:::\n:::\n\n\nLa distribución global es simétrica pareciera existir un valor atípico.\n\nAhora veamos como es la distribución de la tasa de mortalidad por estado.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Histograma por grupos\ndatos |>\n  ggplot(mapping = aes(x = tasa_mortalidad, fill = estado)) +\n  geom_histogram(binwidth = 10, color = \"white\") +\n  scale_fill_scico_d() + # paleta colorblind-friendly\n  facet_grid(estado ~ .) + # variable estado en filas\n  theme_minimal() # tema claro\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-6-1.png){fig-align='center' width=85%}\n:::\n\n```{.r .cell-code}\n# Boxplot por grupos\ndatos |>\n  ggplot(mapping = aes(x = estado, y = tasa_mortalidad, fill = estado)) +\n  geom_boxplot() +\n  scale_fill_scico_d() + # paleta colorblind-friendly\n  theme_minimal() + # tema claro\n  theme(axis.text.x = element_text(angle = 90)) # gira etiquetas eje x\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-6-2.png){fig-align='center' width=85%}\n:::\n:::\n\n\nObservamos que las distribuciones en algunos grupos parecen simétricas y hay diferencias visuales entre las medianas. Esto plantea la pregunta de si dichas diferencias son estadísticamente significativas.\n\n### Análisis de supuestos\n\nSi bien es más recomendable y habitual realizar el análisis de supuestos a partir de los residuales del modelo, podemos chequear que la variable dependiente cumpla con los supuestos de normalidad y homocedasticidad previo a realizar el análisis.\n\n#### Normalidad\n\nUsamos el test de Kolmogorov-Smirnov con corrección de Lilliefors para grupos con más de 50 observaciones con la función `lillie.test()` del paquete `nortest`. Como algunos grupos tienen menos de 50 observaciones, también podríamos utilizar el test de Shapiro-Wilk mediante la función `shapiro.test()` de R `base`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"New York\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"New York\"), tasa_mortalidad)\nD = 0.11633, p-value = 0.03637\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"Maine\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"Maine\"), tasa_mortalidad)\nD = 0.18801, p-value = 0.1364\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"Massachusetts\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"Massachusetts\"), tasa_mortalidad)\nD = 0.1591, p-value = 0.4377\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"New Jersey\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"New Jersey\"), tasa_mortalidad)\nD = 0.14095, p-value = 0.3387\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"Pennsylvania\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"Pennsylvania\"), tasa_mortalidad)\nD = 0.066685, p-value = 0.6839\n```\n\n\n:::\n\n```{.r .cell-code}\ndatos |>\n  filter(estado == \"Vermont\") |>\n  pull(tasa_mortalidad) |> # con pull() extraemos datos de tasa_mortalidad como vector\n  lillie.test() # aplicamos test de bondad de ajuste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  pull(filter(datos, estado == \"Vermont\"), tasa_mortalidad)\nD = 0.14856, p-value = 0.5497\n```\n\n\n:::\n:::\n\n\nPodemos graficar el comportamiento de la variable dependiente en cada grupo mediante Q-Q plots usando el paquete `ggplot2`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndatos |>\n  ggplot() +\n  geom_qq(mapping = aes(sample = tasa_mortalidad)) +\n  geom_qq_line(mapping = aes(sample = tasa_mortalidad)) +\n  facet_wrap(~estado) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-8-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\n#### Homocedasticidad\n\nVerificamos la homogeneidad de varianzas por grupo con el test de Bartlett:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbartlett.test(\n  tasa_mortalidad ~ estado, # utiliza sintaxis fórmula\n  data = datos\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  tasa_mortalidad by estado\nBartlett's K-squared = 4.8185, df = 5, p-value = 0.4384\n```\n\n\n:::\n:::\n\n\nLa variable respuesta cumple con el supuesto de homocedasticidad ($p = 0.438$).\n\n### Análisis de varianza\n\nSi bien podemos realizar un test ANOVA mediante la función `aov()` de R `base`, en el contexto de este curso utilizaremos la función `lm()` del paquete `stats` que usamos anteriormente para ajustar el modelo de [**regresión lineal simple**](04_reg_lineal.qmd)**:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(tasa_mortalidad ~ estado, data = datos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = tasa_mortalidad ~ estado, data = datos)\n\nCoefficients:\n        (Intercept)          estadoMaine  estadoMassachusetts  \n            171.640               11.510               -6.840  \n   estadoNew Jersey   estadoPennsylvania        estadoVermont  \n             -3.007                3.419                4.631  \n```\n\n\n:::\n:::\n\n\nSiempre que trabajemos con modelos, conviene que asignemos los resultados a objetos que luego nos servirán para aplicar otras funciones. Como nuestra variable explicativa es categórica y nuestro principal interés es conocer si existen diferencias significativas entre grupos, no analizaremos los coeficientes del modelo con `summary()`, sino la significancia del test F mediante la función `anova()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# ANOVA\nmodelo <- lm(tasa_mortalidad ~ estado, data = datos)\n\n# Salida del modelo\nanova(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: tasa_mortalidad\n           Df Sum Sq Mean Sq F value   Pr(>F)   \nestado      5   3513  702.67  3.7103 0.003179 **\nResiduals 185  35036  189.38                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nLos resultados del test F nos muestran un $p = 0,003$, sugiriendo que al menos dos grupos son diferentes entre sí.\n\n### Comparaciones múltiples\n\nUna vez que comprobamos que existen diferencias significativas entre grupos, nos interesa saber cuáles grupos son diferentes entre sí. Para ello, existen distintos algoritmos de comparaciones múltiples con sus respectivas correcciones, como el test de *Diferencia Honestamente Significativa de Tukey,* también llamado Tukey HSD o **test de Tukey**. Esta prueba se aplica para grupos equilibrados (mismo tamaño) y varianzas similares (homocedásticas). Es una prueba conservadora, dado que mantiene bajo el error de tipo I, sacrificando la capacidad de detectar diferencias existentes.\n\nSi las varianzas son homocedásticas pero los grupos difieren en tamaño, podemos usar el test de Tukey si tenemos que comparar entre varios grupos, o la **corrección de Bonferroni** para grupos más reducidos.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-condensed table-hover\" style=\"font-family: Calibri; margin-left: auto; margin-right: auto;\">\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;color: white !important;background-color: rgba(47, 46, 78, 255) !important;\"> Código </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;color: white !important;background-color: rgba(47, 46, 78, 255) !important;\"> Rango </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> *** </td>\n   <td style=\"text-align:left;\"> 0 a 0,001 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ** </td>\n   <td style=\"text-align:left;\"> 0,001 a 0,01 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> * </td>\n   <td style=\"text-align:left;\"> 0,01 a 0,05 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> . </td>\n   <td style=\"text-align:left;\"> 0,05 a 0,1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:left;\"> 0,1 a 1 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nEl paquete `emmeans` [@emmeans] es una herramienta muy versátil y poderosa para realizar comparaciones múltiples. Comenzaremos utilizando la función `emmeans()` con el argumento `specs = \"estado\"` para crear un objeto que contenga las medias marginales por grupo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncomp <- emmeans(modelo, specs = \"estado\")\n```\n:::\n\n\nPara realizar las comparaciones múltiples mediante test de Tukey usamos el comando `contrast()` con el argumento `method = \"pairwise\"`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncontrast(comp, method = \"pairwise\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                     estimate   SE  df t.ratio p.value\n New York - Maine               -11.51 3.86 185  -2.983  0.0376\n New York - Massachusetts         6.84 4.07 185   1.680  0.5469\n New York - New Jersey            3.01 3.47 185   0.865  0.9542\n New York - Pennsylvania         -3.42 2.45 185  -1.394  0.7305\n New York - Vermont              -4.63 4.07 185  -1.137  0.8652\n Maine - Massachusetts           18.35 5.04 185   3.644  0.0046\n Maine - New Jersey              14.52 4.57 185   3.179  0.0211\n Maine - Pennsylvania             8.09 3.85 185   2.103  0.2901\n Maine - Vermont                  6.88 5.04 185   1.366  0.7474\n Massachusetts - New Jersey      -3.83 4.75 185  -0.807  0.9659\n Massachusetts - Pennsylvania   -10.26 4.06 185  -2.527  0.1217\n Massachusetts - Vermont        -11.47 5.20 185  -2.205  0.2402\n New Jersey - Pennsylvania       -6.43 3.46 185  -1.857  0.4322\n New Jersey - Vermont            -7.64 4.75 185  -1.609  0.5939\n Pennsylvania - Vermont          -1.21 4.06 185  -0.299  0.9997\n\nP value adjustment: tukey method for comparing a family of 6 estimates \n```\n\n\n:::\n:::\n\n\nLos resultados del test de Tukey nos muestran diferencias significativas en la tasa de mortalidad por cáncer en el estado de Maine respecto de New York, Massachusetts y New Jersey.\n\nPara mayor claridad, podemos mostrar las comparaciones múltiples mediante un gráfico:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(comp) +\n  theme_minimal() # tema claro\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-15-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nEl rombo del medio representa la media marginal para cada grupo y el rectángulo azul, su intervalo de confianza, aquellos grupos en los que no se superponen los intervalos de confianza son estadísticamente diferentes entre sí.\n\n### Bondad de ajuste\n\nEl tamaño de efecto comúnmente utilizado para el caso de ANOVA es $\\eta^2$ (*eta-cuadrado)*, que se calcula como el cociente de la suma de cuadrados del efecto sobre la suma de cuadrados total.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: tasa_mortalidad\n           Df Sum Sq Mean Sq F value   Pr(>F)   \nestado      5   3513  702.67  3.7103 0.003179 **\nResiduals 185  35036  189.38                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# calculo eta-cuadrado\neta2 <- 3513 / (3513 + 35036)\n\neta2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09113077\n```\n\n\n:::\n:::\n\n\nPodemos llegar al mismo valor usando la función `r2()` del paquete `performance`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nr2(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.091\n  adj. R2: 0.067\n```\n\n\n:::\n:::\n\n\n### Potencia\n\nLos test de potencia permiten determinar la probabilidad de encontrar diferencias significativas entre las medias para un determinado nivel de significancia indicando el tamaño de los grupos.\n\nEn base al eta-cuadrado obtenido anteriormente, calculamos el tamaño de efecto convencional mediante la función `cohen.ES()` del paquete `pwr` [@pwr]:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncohen.ES(test = \"anov\", size = \"small\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Conventional effect size from Cohen (1982) \n\n           test = anov\n           size = small\n    effect.size = 0.1\n```\n\n\n:::\n:::\n\n\nLa función `pwr.anova.test()` del paquete `pwr` nos permite calcular la potencia en base al número de grupos, número de observaciones por grupo, tamaño de efecto y nivel de significancia (habitualmente 0,05).\n\nPara grupos de igual tamaño usamos el siguiente código:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npwr.anova.test(k = k, n = n, f = eta_cuadrado, sig.level = 0.05)\n```\n:::\n\n\nEn nuestro ejemplo, donde los tamaños de grupo son diferentes, primero debemos calcular el tamaño de grupo efectivo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Número de grupos\nk <- nlevels(datos$estado)\n\n# Número de observaciones por grupo\nn <- tabyl(datos$estado)$n\n\n# Tamaño de grupo efectivo\nneff <- sum(n)^2 / sum(n^2)\n```\n:::\n\n\nCalculamos la potencia:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npwr.anova.test(k = k, n = neff, f = eta2, sig.level = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Balanced one-way analysis of variance power calculation \n\n              k = 6\n              n = 4.040425\n              f = 0.09113077\n      sig.level = 0.05\n          power = 0.05670154\n\nNOTE: n is number in each group\n```\n\n\n:::\n:::\n\n\n### Análisis de residuales\n\nPara poder dar por válidos los resultados del ANOVA es necesario verificar que se satisfacen las condiciones analizando los residuos del modelo. Para ello, usaremos el mismo procedimiento que vimos para la [**regresión lineal simple**](04_reg_lineal.qmd).\n\nMétodo gráfico con paquete `performance`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_model(modelo)\n```\n\n::: {.cell-output-display}\n![](05_anova_files/figure-html/ej-22-1.png){fig-align='center' width=85%}\n:::\n:::\n\n\nChequeo normalidad de residuales mediante test de Lilliefors:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlillie.test(modelo$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tLilliefors (Kolmogorov-Smirnov) normality test\n\ndata:  modelo$residuals\nD = 0.046833, p-value = 0.388\n```\n\n\n:::\n:::\n\n\nChequeo homocedasticidad (test de Breusch-Pagan):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_heteroscedasticity(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.597).\n```\n\n\n:::\n:::\n\n\nChequeo presencia de outliers (distancia de Cook):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_outliers(modelo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: No outliers detected.\n- Based on the following method and threshold: cook (0.5).\n- For variable: (Whole model)\n```\n\n\n:::\n:::\n\n\n## Conclusión\n\nSe ha realizado un ANOVA de una vía para comparar la tasa de mortalidad por cáncer en seis estados de Estados Unidos. Se encontraron diferencias estadísticamente significativas entre las medias de los grupos ($F = 3,71, p = 0.003$). El *eta-cuadrado* fue de 0.091, lo que indica que el estado de residencia explica un 9.1% de la varianza total en los valores de la tasa de mortalidad por cáncer. La potencia de la prueba estadística fue del 5.7%.\n\nSe realizó la prueba post hoc de Tukey HSD y se encontró que media de mortalidad para el estado de Maine fue estadísticamente superiror respecto de los estados de Massachusetts, New York y New Jersey ($p < 0.05$).\n\n::: {.hidden .only-html}\n@agresti2015\n\n@triola2018\n\n@wickham2019\n\n@gtsummary\n\n@easystats\n\n@nortest\n\n@firke2016\n\n@dlookr\n\n@skimr\n\n@emmeans\n:::\n\n## Referencias",
    "supporting": [
      "05_anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}