{
  "hash": "7e9110532a7dc28690c4ee792fe55117",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Selección de la muestra\"\nauthor: \n  - name: Andrea Silva\n    orcid: 0000-0002-4791-9706\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Introducción\n\nToda investigación epidemiológica requiere, en principio, la selección de una muestra representativa de la población objeto de estudio. Esto implica:\n\n- Determinar el tamaño de la muestra.\n\n- Definir cómo se seleccionarán los sujetos (es decir, las unidades de análisis).\n\n- Calcular la incertidumbre que introduce este proceso de muestreo en nuestras estimaciones.\n\nEl tamaño de la muestra se establece en la fase de diseño del estudio, habitualmente cuando se redacta el protocolo de investigación. Es importante considerar que este tamaño es, en cierto sentido, orientador, ya que su cálculo depende de factores que en ocasiones pueden ser subjetivos o estar limitados por la información previa disponible. Además, las exigencias varían según el objetivo del estudio. Por ejemplo:\n\n- En un estudio transversal, donde se estima una prevalencia, se puede aceptar una precisión menor.\n\n- En un estudio experimental, donde se compara la eficacia de un fármaco frente a un placebo, el tamaño de la muestra debe ser suficiente para detectar una “diferencia significativa” entre los grupos.\n\nCuando el objetivo de la investigación incluye la estimación de un intervalo de confianza (IC) para alguna variable, se busca que dicho IC tenga alta confiabilidad y sea lo más estrecho posible.\n\nEn el caso de los estudios de corte transversal, que se orientan a estimar una proporción, se formulan preguntas como:\\\n— ¿Cuál es la prevalencia, proporción o porcentaje del fenómeno en estudio?\n\nAl tomar una muestra para estimar lo que sucede en la realidad, debemos aceptar que la medición obtenida reflejará la situación poblacional, pero siempre con cierto grado de variabilidad (o error). La **precisión** es ese grado de variabilidad aceptable y se expresa a través de los intervalos de confianza, que definen los límites inferior y superior dentro de los cuales se espera encontrar el verdadero valor del parámetro.\n\n## Cálculo del tamaño muestral\n\nComo se mencionó anteriormente, se requiere conocer algunos datos para el cálculo del tamaño de muestra requerido, entre los que destacan:\n\n- **La proporción esperada del evento:** Aunque resulte paradójico, ya que es el parámetro que se desea estimar, el investigador suele contar con información previa que permite delimitar sus posibles valores. Si no fuera el caso, se utiliza el peor escenario, es decir, una proporción del 50%, ya que este valor maximiza el producto $p(1-p)$ y, por ende, exige el mayor tamaño muestral. De esta forma, muchas veces se recurre a esto para tener al menos una idea del “límite superior” que estaríamos manejando.\n\n- **El nivel de confianza deseado:** Habitualmente se emplea un 95% (lo que equivale a un $\\alpha$ de 0.05). Este valor indica la probabilidad de que el intervalo calculado contenga el parámetro poblacional verdadero. A mayor nivel de confianza (es decir, menor $\\alpha$), mayor es el coeficiente de confiabilidad y, por ende, mayor el tamaño muestral requerido.\n\n- **La precisión (**$\\delta$**) deseada:** Se refiere a la amplitud aceptable del intervalo de confianza. Cuanta más precisión se exija (es decir, un intervalo más estrecho), mayor será el tamaño de la muestra necesario.\n\nLa fórmula para el cálculo es la siguiente:\n\n$$N = \\frac{p.q.(Z\\alpha)^2}{\\delta^2}$$ Donde:\n\n- $N$ es el tamaño muestra requerido.\n- $p$ es la proporción esperada de sujetos portadores del evento.\n- $q = 1 – p$ es la proporción complementaria (sujetos que no tienen la variable en estudio).\n- $\\delta$ es la precisión o magnitud de error aceptable.\n- $Z\\alpha$ es el valor crítico de la distribución normal asociado al nivel de significancia. Se obtiene de tablas de distribución normal de probabilidades y habitualmente se utiliza un valor $\\alpha$ de 0.05, al que le corresponde un valor $Z$ de 1.96\n\nCuando se conoce el tamaño de la población, es necesario aplicar una corrección por población finita:\n\n$$N =\\frac{n^1}{1+\\frac{n^1}{Población}}$$ donde $n^1$ es el $N$ calculado con la ecuación anterior.\n\nEs fundamental entender que el tamaño de la muestra dependerá de $p$ de $\\alpha$ y de la precisión deseada, más que de la complejidad de la fórmula en sí. Existen numerosos softwares que calculan tamaños de muestra. Algunos están especializados en esta tarea (por ejemplo, **EpiDat**, **EpiInfo**, **OpenEp**i), mientras que otros lo incluyen como una opción dentro de un paquete más amplio de análisis. En el lenguaje R, funciones como `power.prop.test()` (para comparación de proporciones) y `power.t.test()` (para pruebas de medias basadas en la distribución $t$ de Student) están incluidas en el paquete `stats`. Otros paquetes útiles incluyen `samplingbook` [@sampling2010], `samplesize` , `pwr` [@champely2006] y `epiR` [@stevenson2025].\n\nA continuación, se presenta un ejemplo práctico utilizando la función `sample.size.prop()` del paquete `samplingbook`. Supongamos que queremos estimar la prevalencia de diabetes en una ciudad de 600,000 habitantes, donde estudios previos sugieren una prevalencia cercana al 10.2%. El objetivo es determinar el tamaño de la muestra en un muestreo aleatorio simple.\n\nComenzamos cargando el paquete requerido:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(samplingbook)\n```\n:::\n\n\nCalculamos el tamaño muestral en base a los siguientes argumentos:\n\n- `e`: número positivo que especifica la precisión que es la mitad del ancho del intervalo de confianza\n- `p:` proporción esperada de eventos con dominio entre los valores 0 y 1.\n- `N`: número entero positivo para el tamaño de la población. El valor predeterminado es `Inf`, lo que significa que los cálculos se realizan sin *corrección de población finita*.\n- `level`: nivel de confianza para los intervalos de confianza. El valor predeterminado es 95%.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample.size.prop(e = 0.02, P = 0.102, N = 600000, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsample.size.prop object: Sample size for proportion estimate\nWith finite population correction: N=6e+05, precision e=0.02 and expected proportion P=0.102\n\nSample size needed: 879\n```\n\n\n:::\n:::\n\n\nEl resultado, tras aplicar la corrección por población finita, indica que se requieren 879 sujetos en la muestra. Por simplicidad, es habitual considerar infinita a la población objetivo, ya que hacerlo así minimiza los riesgos estadísticos:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample.size.prop(e = 0.02, P = 0.102, N = Inf, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsample.size.prop object: Sample size for proportion estimate\nWithout finite population correction: N=Inf, precision e=0.02 and expected proportion P=0.102\n\nSample size needed: 880\n```\n\n\n:::\n:::\n\n\nSi se considera una población infinita, el tamaño muestral calculado es de 880 personas, apenas una unidad más, lo que demuestra que el ajuste por población finita en este caso es mínimo. En cambio, si no se conoce o no se confía en el valor de prevalencia y se opta por el peor escenario ($p = 0.5$):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample.size.prop(e = 0.02, P = 0.5, N = 600000, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nsample.size.prop object: Sample size for proportion estimate\nWith finite population correction: N=6e+05, precision e=0.02 and expected proportion P=0.5\n\nSample size needed: 2392\n```\n\n\n:::\n:::\n\n\nEn este caso, el tamaño muestral aumenta considerablemente hasta 2392 unidades, lo que refleja un enfoque más conservador.\n\nAdemás del cálculo del tamaño muestral, es esencial planificar la forma en que se seleccionarán los individuos. En estudios de corte transversal se debe realizar un muestreo probabilístico, ya que la técnica de muestreo influirá en los factores de expansión necesarios para generalizar los resultados a la población. Aunque el proceso de muestreo no se detalla en este curso, es vital considerarlo para garantizar la validez externa de la investigación.\n\n## Conceptos generales sobre muestreo\n\nUn muestreo se considera **probabilístico** cuando se cumplen dos condiciones fundamentales:\n\n- Es posible conocer de antemano la probabilidad de selección que tiene cada elemento de la población.\n\n- Esta probabilidad es mayor que cero para todos los elementos.\n\nSolo con un muestreo probabilístico se puede medir el grado de precisión de las estimaciones realizadas, ya que se conocen las probabilidades de inclusión. Algunos de los métodos más usados son: Muestreo aleatorio simple, muestreo sistemático en fases, Muestreo aleatorio estratificado, muestreo por conglomerados, etc.\n\n### Muestreo aleatorio simple (MAS)\n\nEn el MAS, cada elemento de la población tiene la misma probabilidad de ser seleccionado (es decir, es un método **equiprobabilístico**). La probabilidad de inclusión se expresa como:\n\n$$P = \\frac{n}{N} $$\n\ndonde:\n\n- $n$ es el tamaño de la muestra,\n\n- $N$ es el tamaño de la población.\n\nEste método requiere contar con un listado completo de la población y se utiliza principalmente en poblaciones cerradas (por ejemplo, escuelas, cárceles, hospitales o muestras de laboratorio), donde los elementos pueden identificarse y numerarse fácilmente.\n\n### Muestreo sistemático (MS)\n\nEl muestreo sistemático es un procedimiento alternativo al MAS, adecuado para la selección de muestras equiprobabilísticas de poblaciones organizadas según algún orden conocido. Sus ventajas incluyen no requerir necesariamente un listado completo de todas las unidades, lo que resulta útil, por ejemplo, para seleccionar a los usuarios que llegan a un servicio hospitalario durante un período determinado.\n\nEl procedimiento consiste en:\n\n1.  Asignar a cada elemento de la población un número del 1 a $N$.\n\n2.  Calcular el intervalo de selección:\n\n    $$k = \\frac{N}{n}$$\n\n3.  Seleccionar aleatoriamente un número $r$ entre 1 y $k$.\n\n4.  Elegir los elementos que ocupan las posiciones: $r, r+k, r + 2k,...$, es decir, la secuencia $r, r+jk$ con $j = 0, 1, 2, \\dots$.\n\nLa probabilidad de ser seleccionado es igual que en el MAS\n\n$$P = \\frac{n}{N} $$\n\n### Muestreo aleatorio estratificado (MAE)\n\nEste método se emplea cuando la población puede dividirse en subgrupos o **estratos** que difieren en las características de interés (por ejemplo, edad, sexo o nivel socioeconómico). La idea es asegurar que cada estrato esté representado en la muestra. El proceso habitual consiste en:\n\n- Elaborar listas separadas para cada estrato.\n\n- Seleccionar una submuestra de cada uno de ellos.\n\nLa probabilidad de selección en cada estrato es:\n\n$$P \\ estrato = \\frac{n \\ estrato}{N \\ estrato} $$\n\nSi se aplica un muestreo proporcional, el tamaño de la muestra en cada estrato se calcula como:\n\n$$n \\ estrato = n\\frac{N \\ estrato}{N} $$\n\nEl objetivo es obtener una muestra cuya variabilidad interna se asemeje a la de la población, logrando que los estratos sean internamente homogéneos y heterogéneos entre sí.\n\n### Muestreo por conglomerados monoetápico\n\nEl muestreo por conglomerados es ideal cuando la población es difícil de delimitar o está muy dispersa. Se divide la población en **conglomerados** (o grupos) que actúan como unidades de primera etapa (UPE) y no deben solaparse.\n\nLa población se divide en grupos (por ejemplo, áreas geográficas, instituciones o servicios). Se selecciona una muestra de $n$ conglomerados y se incluyen **todos** las unidades de análisis de los conglomerados seleccionados. El tamaño del conglomerado se refiere al número de unidades elementales que contiene, pudiendo ser de igual o distinto tamaño. Los conglomerados deberían ser lo más heterogéneos dentro de ellos y lo más homogéneos entre ellos.\n\n### Muestreo por conglomerados bietápico\n\nSe utiliza cuando existe gran variabilidad en el tamaño de los conglomerados o la población es muy grande. En este caso, después de dividir la población en conglomerados y seleccionar algunos de ellos como UPE, se realiza una subselección (muestreo secundario) de los elementos dentro de los conglomerados elegidos.\n\nExisten más posibilidades, que no abordaremos aquí, pero sí nos detendremos en discutir qué implicaciones tiene el muestreo en el proceso de estimación.\n\n### Implicaciones en la Estimación y Ponderación\n\nEn métodos equiprobabilísticos (como el MAS o el MS), cada elemento tiene la misma probabilidad de selección. Sin embargo, en diseños muestrales más complejos (como el muestreo estratificado o por conglomerados), las probabilidades de selección pueden variar entre individuos.\n\nEn estos casos, la probabilidad total de selección de un individuo es el producto de las probabilidades de selección en cada etapa del muestreo. Una vez conocida esta probabilidad, se calcula el peso (o **factor de expansión**) como su inverso. Este peso se interpreta como el número de individuos en la población que representa cada individuo de la muestra.\n\n> El factor de expansión se interpreta como *la cantidad de personas en la población, que representa una persona en la muestra*.\n\nEl factor de expansión se utiliza para extrapolar los resultados obtenidos en la muestra a la población total. Por ejemplo, para estimar un total poblacional para una variable, se pondera el valor medido en cada individuo por su factor de expansión y se suman dichos valores.\n\n## Ejemplo práctico\n\nSupongamos que queremos estimar la prevalencia de sobrepeso/obesidad en estudiantes de enseñanza media de una localidad. Se tiene la siguiente información:\n\n- **Población total de alumnos:** 966\n\n- **Número de escuelas (conglomerados):** 21\n\n- **Tamaño de la muestra global (ya calculado):** 120 alumnos\n\nSi se realizara un **muestreo aleatorio simple (MAS)**, se necesitaría disponer del listado completo de los 966 alumnos y, mediante un sorteo, seleccionar 120 individuos. En ese caso, la probabilidad de selección para cada alumno sería:\n\n$$P = \\frac{n}{N} = \\frac{120}{966}=0,124$$\n\nSupongamos ahora que decide realizar un muestreo por conglomerados biétapico. Cada escuela se considera un conglomerado; se seleccionan 10 de las 21 escuelas por MAS y, dentro de cada escuela seleccionada, se elige una submuestra de estudiantes también mediante MAS. Se decide que el número de estudiantes elegidos en cada conglomerado sea igual para todos.\n\nLos datos globales quedan de la siguiente forma:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gheigtammc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gheigtammc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gheigtammc thead, #gheigtammc tbody, #gheigtammc tfoot, #gheigtammc tr, #gheigtammc td, #gheigtammc th {\n  border-style: none;\n}\n\n#gheigtammc p {\n  margin: 0;\n  padding: 0;\n}\n\n#gheigtammc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gheigtammc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gheigtammc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gheigtammc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gheigtammc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gheigtammc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gheigtammc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gheigtammc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gheigtammc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gheigtammc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gheigtammc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gheigtammc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gheigtammc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gheigtammc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gheigtammc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gheigtammc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gheigtammc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gheigtammc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gheigtammc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gheigtammc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gheigtammc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gheigtammc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gheigtammc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gheigtammc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gheigtammc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gheigtammc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gheigtammc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gheigtammc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gheigtammc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gheigtammc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gheigtammc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gheigtammc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gheigtammc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gheigtammc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gheigtammc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gheigtammc .gt_left {\n  text-align: left;\n}\n\n#gheigtammc .gt_center {\n  text-align: center;\n}\n\n#gheigtammc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gheigtammc .gt_font_normal {\n  font-weight: normal;\n}\n\n#gheigtammc .gt_font_bold {\n  font-weight: bold;\n}\n\n#gheigtammc .gt_font_italic {\n  font-style: italic;\n}\n\n#gheigtammc .gt_super {\n  font-size: 65%;\n}\n\n#gheigtammc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gheigtammc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gheigtammc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gheigtammc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gheigtammc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gheigtammc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gheigtammc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#gheigtammc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#gheigtammc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a-\"> </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Población\">Población</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Muestra\">Muestra</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\" \" class=\"gt_row gt_left\">Tamaño total</td>\n<td headers=\"Población\" class=\"gt_row gt_right\">966</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">120</td></tr>\n    <tr><td headers=\" \" class=\"gt_row gt_left\">Número de conglomerados</td>\n<td headers=\"Población\" class=\"gt_row gt_right\">21</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">10</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nLa decisión de cuántos conglomerados forman parte de la muestra, es una decisión del investigador: a veces puede ser necesario fijar un número, a veces puede ser más conveniente fijar el tamaño de la muestra en cada conglomerado. Por otra parte, puede que decidamos que el número de sujetos seleccionados en cada conglomerado sea igual para todos; que sea una fracción fija o algo a definir.\n\nDentro de los conglomerados seleccionados, se obtiene la siguiente distribución (en este ejemplo, la suma de los tamaños de los conglomerados seleccionados es 480 y en cada uno se eligen 12 alumnos):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dmqugrzujz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dmqugrzujz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dmqugrzujz thead, #dmqugrzujz tbody, #dmqugrzujz tfoot, #dmqugrzujz tr, #dmqugrzujz td, #dmqugrzujz th {\n  border-style: none;\n}\n\n#dmqugrzujz p {\n  margin: 0;\n  padding: 0;\n}\n\n#dmqugrzujz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dmqugrzujz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dmqugrzujz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dmqugrzujz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dmqugrzujz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dmqugrzujz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dmqugrzujz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dmqugrzujz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dmqugrzujz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dmqugrzujz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dmqugrzujz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dmqugrzujz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dmqugrzujz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dmqugrzujz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dmqugrzujz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmqugrzujz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dmqugrzujz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dmqugrzujz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dmqugrzujz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmqugrzujz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dmqugrzujz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmqugrzujz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dmqugrzujz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmqugrzujz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmqugrzujz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmqugrzujz .gt_left {\n  text-align: left;\n}\n\n#dmqugrzujz .gt_center {\n  text-align: center;\n}\n\n#dmqugrzujz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dmqugrzujz .gt_font_normal {\n  font-weight: normal;\n}\n\n#dmqugrzujz .gt_font_bold {\n  font-weight: bold;\n}\n\n#dmqugrzujz .gt_font_italic {\n  font-style: italic;\n}\n\n#dmqugrzujz .gt_super {\n  font-size: 65%;\n}\n\n#dmqugrzujz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dmqugrzujz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dmqugrzujz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dmqugrzujz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dmqugrzujz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dmqugrzujz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dmqugrzujz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dmqugrzujz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dmqugrzujz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Conglomerado\">Conglomerado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Tamaño\">Tamaño</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Muestra\">Muestra</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">5.1</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">48</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">1.3</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">28</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">2.3</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">64</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">2.2</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">43</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">3.1</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">37</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">5.3</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">86</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">1.4</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">37</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">3.3</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">56</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">2.4</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">48</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">1.5</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">33</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">12</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Tamaño\" class=\"gt_row gt_right\">480</td>\n<td headers=\"Muestra\" class=\"gt_row gt_right\">120</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Cálculo de las Probabilidades de Selección y Ponderaciones\n\nPara que un individuo sea seleccionado en este diseño, debe ocurrir primero que su conglomerado sea escogido y, posteriormente, que él sea seleccionado dentro de ese conglomerado. Si asumimos que:\n\n> *“Dos sucesos son independientes si la probabilidad de que ocurran ambos simultáneamente es igual al producto de las probabilidades de que ocurra cada uno de ellos”*.\n\nLa probabilidad total de selección es el producto de:\n\n1.  La probabilidad de que el conglomerado sea seleccionado:\n\n    $$P_{conglomerado} = \\frac{10}{21}$$\n\n2.  La probabilidad de que un individuo sea seleccionado dentro de su conglomerado:\n\n    $$P_{dentro} = \\frac{N°~alumnos~en~la~muestra~del~conglomerado}{Tamaño~del~conglomerado}$$\n\nPara los individuos del conglomerado 5.1; la probabilidad de selección será:\n\n$$P_{5.1} = \\frac{10}{21}*\\frac{12}{48} \\approx 0,1190 \\quad (11.9\\%)$$\n\nLa ponderación o **factor de expansión** se obtiene como el inverso de la probabilidad de selección:\n\n$$w = \\frac{1}{P}$$\n\nEs decir:\n\n$$w_{5.1} = \\frac{1}{1.190} \\approx 8.4$$\n\nEsto significa que cada alumno seleccionado del conglomerado 5.1 representa aproximadamente a 8 alumnos de la población.\n\nSi se realizan los cálculos para cada uno de los conglomerados, se obtiene la siguiente tabla:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"hlnpnkmwyh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hlnpnkmwyh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hlnpnkmwyh thead, #hlnpnkmwyh tbody, #hlnpnkmwyh tfoot, #hlnpnkmwyh tr, #hlnpnkmwyh td, #hlnpnkmwyh th {\n  border-style: none;\n}\n\n#hlnpnkmwyh p {\n  margin: 0;\n  padding: 0;\n}\n\n#hlnpnkmwyh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hlnpnkmwyh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hlnpnkmwyh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hlnpnkmwyh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hlnpnkmwyh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hlnpnkmwyh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hlnpnkmwyh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hlnpnkmwyh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hlnpnkmwyh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hlnpnkmwyh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hlnpnkmwyh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hlnpnkmwyh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hlnpnkmwyh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hlnpnkmwyh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hlnpnkmwyh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlnpnkmwyh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hlnpnkmwyh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hlnpnkmwyh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hlnpnkmwyh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlnpnkmwyh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hlnpnkmwyh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlnpnkmwyh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hlnpnkmwyh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlnpnkmwyh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hlnpnkmwyh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hlnpnkmwyh .gt_left {\n  text-align: left;\n}\n\n#hlnpnkmwyh .gt_center {\n  text-align: center;\n}\n\n#hlnpnkmwyh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hlnpnkmwyh .gt_font_normal {\n  font-weight: normal;\n}\n\n#hlnpnkmwyh .gt_font_bold {\n  font-weight: bold;\n}\n\n#hlnpnkmwyh .gt_font_italic {\n  font-style: italic;\n}\n\n#hlnpnkmwyh .gt_super {\n  font-size: 65%;\n}\n\n#hlnpnkmwyh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hlnpnkmwyh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hlnpnkmwyh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hlnpnkmwyh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hlnpnkmwyh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hlnpnkmwyh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hlnpnkmwyh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hlnpnkmwyh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hlnpnkmwyh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Conglomerado\">Conglomerado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Probabilidad\">Probabilidad</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Ponderación\">Ponderación</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">5.1</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">11.90</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">8.40</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">1.3</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">20.41</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">4.90</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">2.3</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">8.93</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">11.20</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">2.2</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">13.29</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">7.53</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">3.1</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">15.44</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">6.48</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">5.3</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">6.65</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">15.05</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">1.4</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">15.44</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">6.48</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">3.3</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">10.20</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">9.80</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">11.90</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">8.40</td></tr>\n    <tr><td headers=\"Conglomerado\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"Probabilidad\" class=\"gt_row gt_right\">17.32</td>\n<td headers=\"Ponderación\" class=\"gt_row gt_right\">5.78</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nCada individuo seleccionado en el estudio tiene una probabilidad de inclusión que depende tanto de la probabilidad de que su escuela (conglomerado) sea seleccionada como de la probabilidad de que él sea elegido dentro de su escuela. La ponderación resultante (el inverso de esta probabilidad) se utiliza para \"expandir\" el resultado del estudio, de manera que cada alumno en la muestra represente a un número determinado de alumnos en la población total.\n\nPor ejemplo, en el conglomerado 5.1, cada alumno seleccionado representa aproximadamente a 8 alumnos de la población. De este modo, al calcular la prevalencia de sobrepeso/obesidad en la muestra, se aplican estos factores de expansión para obtener estimaciones que sean representativas de los 966 alumnos de la localidad.\n\nEste proceso es fundamental en estudios basados en muestreos complejos, ya que permite corregir posibles diferencias en las probabilidades de selección y garantizar que las estimaciones sean válidas y precisas para toda la población.\n\n::: hidden\n@hernández-ávila2011\n\n@daniel2002\n\n@rodríguez2018\n\n@ríusdíaz2012\n\n@triola2018\n\n@alvarezcaceres2007\n\n@norman1996\n\n@bioestad2006a\n\n@vonelm2008\n\n@schulz2010\n\n@field2014\n\n@rodríguez2003\n\n@epidat4\n:::\n\n## Referencias",
    "supporting": [
      "05_muestreo_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}